/*
 * TIMER_Config.h
 *
 *  Created on: 21 Sep 2021
 *      Author: Viro
 */

#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_

/* TIMER0_MODE OPTIONS :
 * 1- TIMER0_NORMAL_MODE
 * 2- TIMER0_CTC_MODE
 * 3- TIMER0_PWM_PHASECORRECT_MODE
 * 4- TIMER0_PMW_FAST_MODE*/
#define TIMER0_MODE TIMER0_CTC_MODE

/*PRESCALER OPTIONS:
 * 1- TIMER0_NO_PRESCALER
 * 2- TIMER0_8_PRESCALER
 * 3- TIMER0_64_PRESCALER
 * 4- TIMER0_256_PRESCALER
 * 5- TIMER0_1024_PRESCALER
 * 6- TIMER0_EXTERNAL_SOURCE_FALLING
 * 7- TIMER0_EXTERNAL_SOURCE_RISING  */
#define TIMER0_PRESCALER TIMER0_1024_PRESCALER

/*OC0 OPTION
 * 1-OC0_PIN_DISCONNECT
 * 2-OC0_PIN_TOGGLE
 * 3-OC0_PIN_CLEAR
 * 4-OC0_PIN_SET*/
#define OC0_PIN_MODE OC0_PIN_TOGGLE

#endif /* TIMER_CONFIG_H_ */
